---
title: "Practical Four"
format: html
---

## Question 1

```{r}
library(UtilsDataRSV)
library(nycflights13)
library(dplyr)
head(flights)
UtilsDataRSV::view_cols(flights)

```

## Question 2

```{r}

flight1 <- flights |> filter(month == 1)

carrier_vec <- flight1$carrier |> unique() 
carrier_dist_vec_mean <- length(carrier_vec) |> numeric()
carrier_dist_vec_sd <- length(carrier_vec) |> numeric()

for (i in seq_along(carrier_vec)) {
  carrier_dist_vec_mean[i]<- flight1 |> as_tibble() |> filter(carrier == carrier_vec[i]) |> pull(distance) |>mean()
  
  carrier_dist_vec_sd[i]<- flight1 |> as_tibble() |> filter(carrier == carrier_vec[i]) |> pull(distance) |> sd()
}

dist_tbl <- tibble(
  carrier = carrier_vec,
  mean_distance = carrier_dist_vec_mean,
  sd_distance = carrier_dist_vec_sd
)

dist_tbl <- dist_tbl |> arrange(mean_distance)
dist_tbl
```

## Question 3

```{r}



```

## Question 4

```{r}
data <- flights |> select(dep_delay, carrier, month) |> arrange(month)

data2 <- data |>
  summarise(mean_dep_delay = mean(dep_delay, na.rm = TRUE), .by = c(month, carrier))

df <- data2 |> pivot_wider(
  id_cols = ("month"),
  names_from = ("carrier"),
  values_from = ("mean_dep_delay")
)
df
```

## Question 5

```{r}
total_flights <- flights |> nrow()

flights_int <- flights |> filter(dep_delay>0) |> filter(arr_delay<= 0)

prop_flights <- nrow(flights_int)/total_flights
prop_flights
```

## Question 6

### 6.1

```{r}
multi_al_rout <- flights |> group_by(origin,dest) |> summarise(n_al = n_distinct(carrier), .groups = "drop") |> filter(n_al >1)

multi_al_rout
```

### 6.2

```{r}
 avg_arr_del <- flights |> inner_join(multi_al_rout, by = c("origin", "dest")) |> group_by(origin,dest,carrier) |> summarise(avg_arr_del=mean(arr_delay,na.rm=TRUE), .groups = "drop")
 
 avg_arr_del
```

### 6.3

```{r}
avg_arr_del_airlines <- avg_arr_del |> left_join(airlines, by = "carrier") 

route_results <- avg_arr_del_airlines |> group_by(origin,dest) |>
  summarise(
    fastest_airline = name[which.max(avg_arr_del)],
    fastest_airline_del = min(avg_arr_del, na.rm = TRUE),
    slowest_airline = name[which.min(avg_arr_del)],
    slowest_airline_del = max(avg_arr_del, na.rm = TRUE),
    .groups = "drop"
  )
```

### 6.4

```{r}
route_arr_del_diff <- route_results |> mutate(del_diff = fastest_airline_del - slowest_airline_del)

route_max_del_diff <- route_arr_del_diff |> slice_max(abs(del_diff))

route_max_del_diff
```

### 6.5
